// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwOKo_vjYygx0cx8UoKXNBPUaCWQ25888',
    appId: '1:982180459980:web:77d1dd451ccf387d43d969',
    messagingSenderId: '982180459980',
    projectId: 'app-richard-c3c90',
    authDomain: 'app-richard-c3c90.firebaseapp.com',
    storageBucket: 'app-richard-c3c90.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaNcSOpoF6zMyEP5BUzgjr1MeR18rMDN4',
    appId: '1:982180459980:android:d4b6159b6322c40243d969',
    messagingSenderId: '982180459980',
    projectId: 'app-richard-c3c90',
    storageBucket: 'app-richard-c3c90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlvQyZKQFjTmXyWTST8bCgFxKxWqOdDwE',
    appId: '1:982180459980:ios:898ede78678a1fd843d969',
    messagingSenderId: '982180459980',
    projectId: 'app-richard-c3c90',
    storageBucket: 'app-richard-c3c90.firebasestorage.app',
    iosBundleId: 'com.example.appRichard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlvQyZKQFjTmXyWTST8bCgFxKxWqOdDwE',
    appId: '1:982180459980:ios:898ede78678a1fd843d969',
    messagingSenderId: '982180459980',
    projectId: 'app-richard-c3c90',
    storageBucket: 'app-richard-c3c90.firebasestorage.app',
    iosBundleId: 'com.example.appRichard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwOKo_vjYygx0cx8UoKXNBPUaCWQ25888',
    appId: '1:982180459980:web:d45d8f7d29cd609443d969',
    messagingSenderId: '982180459980',
    projectId: 'app-richard-c3c90',
    authDomain: 'app-richard-c3c90.firebaseapp.com',
    storageBucket: 'app-richard-c3c90.firebasestorage.app',
  );
}
